### ISSUE TITLE
Revit encountered a System.Exception: The component 'RevitAddinManager.View.FrmAddInManager' does not have a resource identified by the URI 

### ISSUE THREAD

**Issue by chuongmep** [chuongmep/RevitAddInManager#7]
**Describe the bug**
Revit encountered a System.Exception: The component 'RevitAddinManager.View.FrmAddInManager' does not have a resource identified by the URI '/RevitAddinManager;component/view/frmaddinmanager.xaml'.
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at RevitAddinManager.View.FrmAddInManager..ctor(AddInManagerViewModel vm)
   at RevitAddinManager.Command.AddinManagerBase.ExecuteCommand(ExternalCommandData data, String& message, ElementSet elements, Boolean faceless)
   at RevitAddinManager.Command.AddInManagerManual.Execute(ExternalCommandData commandData, String& message, ElementSet elements)
   at apiManagedExecuteCommand(AString* assemblyName, AString* className, AString* vendorDescription, MFCApp* pMFCApp, DBView* pDBView, AString* message, Set<ElementId\,std::less<ElementId>\,tnallc<ElementId> >* ids, Map<AString\,AString\,std::less<AString>\,tnallc<std::pair<AString const \,AString> > >* data, AString* exceptionName, AString* exceptionMessage)

**To Reproduce**
1. Go to Addin Open Add-in Manager
2. Click Load dll Add-in manager to Add-in Manager
3. Run AddinManager loaded
4. Open again Add-in Manager from ribbon
5. See Error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31106432/150962186-e861c4fe-24f2-480b-82bc-a76d04ff0737.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Revit 2023

**Comment by chuongmep** [comment]
Use small trick to trim assembly version in project configuration 
```
<PropertyGroup>
 <PublishSingleFile>true</PublishSingleFile>
      <PublishTrimmed>true</PublishTrimmed>
    </PropertyGroup>
```

**Comment by chuongmep** [comment]
This problem occurs when Assembly.LoadFile method is used to load assemblies at runtime. But when Assembly.LoadFrom method is used, it does not occur.

**Comment by chuongmep** [comment]
https://chowdera.com/2022/03/202203091902109000.html

**Comment by chuongmep** [comment]
System.InvalidCastException: [A]RevitAddinManager.View.Control.ExtendedTreeView cannot be cast to [B]RevitAddinManager.View.Control.ExtendedTreeView. Type A originates from 'RevitAddinManager, Version=2022.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'LoadNeither' at location 'C:\Users\Chuong.Ho\AppData\Local\Temp\RevitAddins\RevitAddinManager-Executing-20220529_151417_2606\RevitAddinManager.dll'. Type B originates from 'RevitAddinManager, Version=2023.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'LoadFrom' at location 'C:\Users\Chuong.Ho\AppData\Roaming\Autodesk\Revit\Addins\2023\RevitAddinManager\RevitAddinManager.dll'.
   at RevitAddinManager.View.FrmAddInManager.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target) in D:\API\Revit\RevitAddInManager\AddInManager\View\FrmAddInManager.xaml:line 0
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)

**Comment by chuongmep** [comment]
https://github.com/dotnet/wpf/issues/1700

**Comment by chuongmep** [comment]
https://github.com/dotnet/wpf/issues/4494

**Comment by chuongmep** [comment]
@lishuangquan1987 still not yet, it problem from core of wpf, error same when change to in net 4.7.2, you can read some acticle a has report in main github wpf open source in https://github.com/dotnet/wpf/issues/1700
